#!/bin/bash
# Script para ayudar a configurar variables en Vercel
# Uso: bash scripts/setup-vercel-vars.sh

echo "🔧 CONFIGURACIÓN DE VARIABLES EN VERCEL"
echo "=================================="
echo ""
echo "⚠️  Necesitas tener acceso al dashboard de Vercel:"
echo "   https://vercel.com/evigueras-projects/cobro-detector/settings/environment-variables"
echo ""
echo "📋 VARIABLES REQUERIDAS:"
echo ""
echo "1. UPSTASH_REDIS_URL"
echo "   - Ir a: https://upstash.com → Create Database"
echo "   - Copiar URL (ejemplo: https://xxx.upstash.io)"
echo ""
echo "2. UPSTASH_REDIS_TOKEN"
echo "   - Mismo sitio de Upstash → Copiar Token"
echo ""
echo "3. MERCADOPAGO_WEBHOOK_SECRET"
echo "   - Ir a: https://www.mercadopago.cl/developers/panel/credentials"
echo "   - Copiar Webhook Secret"
echo ""
echo "=================================="
echo ""
echo "📝 INSTRUCCIONES:"
echo "1. Ve al dashboard de Vercel (URL arriba)"
echo "2. Click en 'Add Variable'"
echo "3. Agrega cada variable con su valor"
echo "4. Selecciona entornos: Production, Preview, Development"
echo "5. Click 'Save'"
echo ""
echo "=================================="
echo ""
echo "⚡️ OPCIONAL (para Rate Limiting):"
echo "   Si no configuras Upstash, el rate limiting NO funcionará"
echo "   pero la aplicación sí funcionará."
echo ""
echo "✅ DESPUÉS DE CONFIGURAR:"
echo "   Ejecuta: npx vercel --prod"
echo "   O haz push: git push origin main"
